analysis:
  demographics:
    age_backend: retinaface
    age_model: Age
    attributes:
    - age
    - gender
    - race
    - emotion
    confidence_threshold: 0.7
    detection_interval: 30
    embedding_normalize: true
    embedding_similarity_threshold: 0.4
    embedding_window_size: 100
    emotion_backend: retinaface
    emotion_model: Emotion
    enabled: true
    face_match_backend: model
    face_match_threshold: 0.8
    gender_backend: retinaface
    gender_model: Gender
    min_face_size: 50
    model: deepface
    model_dir: ./models
    one_time_demographics: true
    race_backend: retinaface
    race_model: Race
    use_insightface: true
  dwell_time:
    enabled: true
    min_duration: 5
  heatmap:
    decay_factor: 0.1
    enabled: true
    grid_size: 0.5
camera:
  backend: pyav
  buffer_size: 1
  connection_timeout: 20.0
  fps: 15
  frame_skip_on_error: true
  h264_error_threshold: 20
  max_decode_errors: 50
  max_retries: -1
  min_frame_size: 100
  password: reviision
  process_latest_only: true
  recovery_frame_count: 5
  resolution:
  - 1280
  - 720
  retry_interval: 3.0
  rtsp_transport: tcp
  timeout: 20.0
  type: rtsp
  url: rtsp://reviision:reviision@192.168.4.31:554/stream1
  username: reviision
database:
  path: reviision.db
  type: sqlite
detection:
  confidence_threshold: 0.5
  iou_threshold: 0.45
  model: yolov8n.pt
heatmap:
  decay_factor: 0.1
  grid_size: 0.5
logging:
  level: INFO
tracking:
  confirmation_frames: 12
  demographic_consistency_threshold: 0.8
  distance_threshold: 120
  feature_similarity_threshold: 0.85
  feature_weight: 0.4
  iou_threshold: 0.2
  max_age: 45
  min_confidence_for_db: 0.75
  min_frames_for_db: 12
  min_hits: 8
  min_track_confidence: 0.4
  position_weight: 0.6
  reid_distance_threshold: 250
  reid_enabled: true
  reid_feature_threshold: 0.75
  reid_max_age: 120
  spatial_threshold: 100
  temporal_window: 30.0
web:
  create_default_admin: true
  debug: true
  host: 0.0.0.0
  lockout_duration_minutes: 15
  max_login_attempts: 5
  port: 5000
  secret_key: abcdefghijklmnopqrstuvwxyz1234
  session_timeout_hours: 2
