analysis:
  demographics:
    age_backend: opencv
    age_model: Age
    attributes:
    - age
    - gender
    - race
    - emotion
    confidence_threshold: 0.7
    detection_interval: 30
    emotion_backend: opencv
    emotion_model: Emotion
    enabled: true
    gender_backend: opencv
    gender_model: Gender
    min_face_size: 50
    model: deepface
    model_dir: ./models
    race_backend: opencv
    race_model: Race
    use_insightface: true
  dwell_time:
    enabled: true
    min_duration: 5
  heatmap:
    decay_factor: 0.1
    enabled: true
    grid_size: 0.5
camera:
  password: reviision
  url: rtsp://reviision:reviision@192.168.1.60:8554/stream1
  type: rtsp
  username: reviision
database:
  path: reviision.db
  type: sqlite
detection:
  confidence_threshold: 0.5
  iou_threshold: 0.45
  model: yolov8n.pt
heatmap:
  decay_factor: 0.1
  grid_size: 0.5
logging:
  level: INFO
tracking:
  iou_threshold: 0.15
  max_age: 30
  min_hits: 3
web:
  create_default_admin: true
  debug: true
  host: 0.0.0.0
  lockout_duration_minutes: 15
  max_login_attempts: 5
  port: 5000
  secret_key: abcdefghijklmnopqrstuvwxyz1234
  session_timeout_hours: 2
