analysis:
  demographics:
    age_backend: retinaface
    age_model: Age
    attributes:
    - age
    - gender
    - race
    - emotion
    confidence_threshold: 0.7
    detection_interval: 30
    emotion_backend: retinaface
    emotion_model: Emotion
    enabled: true
    gender_backend: retinaface
    gender_model: Gender
    min_face_size: 50
    model: deepface
    model_dir: ./models
    race_backend: retinaface
    race_model: Race
    use_insightface: true
    one_time_demographics: true  # Only analyze demographics once per person
    embedding_similarity_threshold: 0.4  # Stricter for better ReID
    embedding_normalize: true  # Normalize embeddings before comparison
    embedding_window_size: 100  # Rolling window size for recent embeddings
    face_match_backend: model  # 'model' for dedicated face verification, 'cosine' for cosine similarity
    face_match_threshold: 0.8  # Higher threshold for model-based matching
  dwell_time:
    enabled: true
    min_duration: 5
  heatmap:
    decay_factor: 0.1
    enabled: true
    grid_size: 0.5
camera:
  password: reviision
  #url: rtsp://reviision:reviision@172.20.10.3:8554/stream1
  url: rtsp://reviision:reviision@192.168.4.31:554/stream1
  type: rtsp
  username: reviision
  buffer_size: 1  # Reduced buffer for better H.264 error recovery
  timeout: 20.0
  retry_interval: 3.0
  max_retries: -1
  rtsp_transport: tcp
  connection_timeout: 20.0
  fps: 15
  resolution: [1280, 720]
  process_latest_only: true  # Always process the latest frame, drop stale frames
  backend: pyav  # Use 'pyav' (FFmpeg) for RTSP frame grabbing
  # H.264 Error Handling Configuration
  h264_error_threshold: 20      # Max consecutive H.264 errors before reconnection
  frame_skip_on_error: true     # Enable frame skipping for error recovery
  recovery_frame_count: 5       # Number of frames to skip during recovery
  min_frame_size: 100          # Minimum valid frame size in pixels
  max_decode_errors: 50        # Max decode errors before extended delay
database:
  path: reviision.db
  type: sqlite
detection:
  confidence_threshold: 0.5
  iou_threshold: 0.45
  model: yolov8n.pt
heatmap:
  decay_factor: 0.1
  grid_size: 0.5
logging:
  level: INFO
tracking:
  # Enhanced tracking parameters for duplicate reduction
  iou_threshold: 0.2
  max_age: 45
  min_hits: 8
  distance_threshold: 120
  feature_weight: 0.4
  position_weight: 0.6
  min_track_confidence: 0.4
  confirmation_frames: 12

  # Re-identification settings
  reid_enabled: true
  reid_distance_threshold: 250
  reid_feature_threshold: 0.75
  reid_max_age: 120

  # Duplicate reduction settings
  min_frames_for_db: 12
  min_confidence_for_db: 0.75
  demographic_consistency_threshold: 0.8
  feature_similarity_threshold: 0.85
  temporal_window: 30.0
  spatial_threshold: 100
web:
  create_default_admin: true
  debug: true
  host: 0.0.0.0
  lockout_duration_minutes: 15
  max_login_attempts: 5
  port: 5000
  secret_key: abcdefghijklmnopqrstuvwxyz1234
  session_timeout_hours: 2
